export interface MapLocation {
  country: string
  city: string
  coordinator: string
  email: string
  lat: number
  lng: number
}

// Institute Precept Eurasia (generat din instute.csv). Cuba exclus pentru siguranță.
export const locations: MapLocation[] = [
  { country: "Moldova", city: "Cazaclia", coordinator: "Snejana Diulgher", email: "diulger.snejana@gmail.com", lat: 46.0289, lng: 28.6428 },
  { country: "Poland", city: "Szczytno", coordinator: "Andrzej Seweryn", email: "andrzej.seweryn@gmail.com", lat: 53.5626, lng: 20.9857 },
  { country: "Bolivia", city: "Cochabamba", coordinator: "Daniel Cuaquira baltazar", email: "dcuaquira@ministeriosprecepto.org", lat: -17.3895, lng: -66.1568 },
  { country: "Moldova", city: "Chișinău", coordinator: "Vasile Filat", email: "vasile.filat@eurasiaprecept.org", lat: 47.0105, lng: 28.8638 },
  { country: "Ukraine", city: "Mukachevo", coordinator: "Sergey Sobran", email: "sobran1122@gmail.com", lat: 48.4414, lng: 22.7178 },
  { country: "Belarus", city: "Minsk", coordinator: "Shevtsov Aleksandr", email: "shef6840@gmail.com", lat: 53.9006, lng: 27.559 },
  { country: "Ukraine", city: "Kryvyi Rih", coordinator: "Іван Свашенко", email: "svashenko77@gmail.com", lat: 47.9105, lng: 33.3918 },
  { country: "Ukraine", city: "Kovel", coordinator: "Kateryna Hotsyk", email: "katerynahotsyk1999@gmail.com", lat: 51.2117, lng: 24.7086 },
  { country: "Ukraine", city: "Berezne", coordinator: "Anton Tymonishyn", email: "tymonishyn@gmail.com", lat: 51.0033, lng: 26.755 },
  { country: "Sri Lanka", city: "Colombo", coordinator: "Sergiu Filat", email: "filatsergiu_me@me.com", lat: 6.9271, lng: 79.8612 },
  { country: "Russia", city: "Oryol", coordinator: "Zanin Alexander", email: "zanin.an@gmail.com", lat: 52.9704, lng: 36.0635 },
  { country: "South Sudan", city: "Juba", coordinator: "Blendarencu Radu", email: "radu.blendarencu@gmail.com", lat: 4.8594, lng: 31.5713 },
  { country: "Germany", city: "Kehl", coordinator: "Ліна Олексієнко", email: "", lat: 48.5722, lng: 7.8149 },
  { country: "Kazakhstan", city: "Nur-Sultan", coordinator: "Tentiuc Alexei", email: "alexei.tentiuc@gmail.com", lat: 51.1694, lng: 71.4491 },
  { country: "Russia", city: "Abakan", coordinator: "Marina Tapcova", email: "tapcovamarina@gmail.com", lat: 53.7223, lng: 91.4425 },
  { country: "Peru", city: "Lima", coordinator: "Rosario priscila Gonzalez zuzunaga", email: "priscilagonzales@hotmail.com", lat: -12.0464, lng: -77.0428 },
  { country: "Bulgaria", city: "Plovdiv", coordinator: "Vasile Filat", email: "vasile.filat@eurasiaprecept.org", lat: 42.1354, lng: 24.7453 },
  { country: "Ukraine", city: "Bolhrad", coordinator: "Світлана Бєрбат", email: "svetaberbat55@gmail.com", lat: 45.6847, lng: 28.6169 },
  { country: "Germany", city: "Hamburg", coordinator: "Tentiuc Alexei", email: "alexei.tentiuc@gmail.com", lat: 53.5511, lng: 9.9937 },
  { country: "Russia", city: "Vladikavkaz", coordinator: "Zanin Alexander", email: "zanin.an@gmail.com", lat: 43.0367, lng: 44.6678 },
  { country: "Russia", city: "Ulan-Ude", coordinator: "Evgeny Tretyakov", email: "blagovest_deaf@mail.ru", lat: 51.8335, lng: 107.5841 },
  { country: "Moldova", city: "Colibasi", coordinator: "Buzila Alexandru", email: "alexandru.buzila@gmail.com", lat: 45.5069, lng: 28.4386 },
  { country: "Russia", city: "Novokuznetsk", coordinator: "Mihail Bortsaykin", email: "borcaikin-76@mail.ru", lat: 53.7557, lng: 87.1099 },
  { country: "Poland", city: "Warsaw", coordinator: "Karamalak Serghei", email: "srg.karamalak@gmail.com", lat: 52.2297, lng: 21.0122 },
  { country: "Ukraine", city: "Rivne", coordinator: "Natalia Platova", email: "platanrivne@gmail.com", lat: 50.6199, lng: 26.2516 },
  { country: "Czech Republic", city: "Brno", coordinator: "Igor Demkovskyi", email: "demkovskyigor@gmail.com", lat: 49.1951, lng: 16.6068 },
  { country: "Serbia", city: "Belgrade", coordinator: "Sabo Ksenija", email: "ksenijasabo@gmail.com", lat: 44.7866, lng: 20.4489 },
  { country: "Mongolia", city: "Ulaanbaatar", coordinator: "Khaliunaa Dodnoi", email: "dodnoihaliun@gmail.com", lat: 47.8864, lng: 106.9057 },
  { country: "Ukraine", city: "Lutsk", coordinator: "Anton Tymonishyn", email: "tymonishyn@gmail.com", lat: 50.7472, lng: 25.3254 },
  { country: "Ukraine", city: "Khmelnytskyi", coordinator: "Богдан Машталяр", email: "bogdanu_mas-ru@ukr.net", lat: 49.4229, lng: 26.9871 },
  { country: "Bhutan", city: "Thimphu", coordinator: "Blendarencu Radu", email: "radu.blendarencu@gmail.com", lat: 27.4728, lng: 89.639 },
  { country: "Ukraine", city: "Dunaevtsi", coordinator: "Богдан Машталяр", email: "bogdanu_mas-ru@ukr.net", lat: 48.8903, lng: 26.8583 },
  { country: "Ukraine", city: "Zaporizhzhia", coordinator: "Aleksej Hripun", email: "aleksey_photo@ukr.net", lat: 47.8388, lng: 35.1396 },
  { country: "Ukraine", city: "Kiliya", coordinator: "Karamalak Serghei", email: "srg.karamalak@gmail.com", lat: 45.4553, lng: 29.2686 },
  { country: "United States of America", city: "Sacramento", coordinator: "George Neverov", email: "george.neverov@pm.me", lat: 38.5816, lng: -121.4944 },
  { country: "Ukraine", city: "Kyiv", coordinator: "Andrey Grynenko", email: "andrey.grynenko28@gmail.com", lat: 50.4501, lng: 30.5234 },
  { country: "Vietnam", city: "Ho Chi Minh City", coordinator: "Blendarencu Radu", email: "radu.blendarencu@gmail.com", lat: 10.8231, lng: 106.6297 },
  { country: "Ukraine", city: "Kharkiv", coordinator: "Anton Tymonishyn", email: "tymonishyn@gmail.com", lat: 49.9935, lng: 36.2304 },
  { country: "Azerbaijan", city: "Baku", coordinator: "Ирина Сагай", email: "sagaybaku@gmail.com", lat: 40.4093, lng: 49.8671 },
  { country: "Kyrgyzstan", city: "Bishkek", coordinator: "Mirlan Sagynbaev", email: "mirsagyn@gmail.com", lat: 42.8746, lng: 74.5698 },
  { country: "Russia", city: "Saint Petersburg", coordinator: "Zanin Alexander", email: "zanin.an@gmail.com", lat: 59.9311, lng: 30.3609 },
  { country: "Kazakhstan", city: "Almaty", coordinator: "Tentiuc Alexei", email: "alexei.tentiuc@gmail.com", lat: 43.222, lng: 76.8512 },
  { country: "Nepal", city: "Kathmandu", coordinator: "Ajay Chaudhary", email: "raajro@gmail.com", lat: 27.7172, lng: 85.324 },
  { country: "Pakistan", city: "Gujranwala", coordinator: "Sergiu Filat", email: "filatsergiu_me@me.com", lat: 32.1877, lng: 74.1945 },
  { country: "Armenia", city: "Yerevan", coordinator: "Khachatryan Vardan", email: "khachatryan_vardan@yahoo.com", lat: 40.1792, lng: 44.4991 },
  { country: "Greece", city: "Atena", coordinator: "Tentiuc Alexei", email: "alexei.tentiuc@gmail.com", lat: 37.9838, lng: 23.7275 },
  { country: "Thailand", city: "Chiang Rai", coordinator: "Blendarencu Radu", email: "radu.blendarencu@gmail.com", lat: 19.9105, lng: 99.8406 },
  { country: "Romania", city: "Surduc", coordinator: "Olariu Gigel", email: "olariugigel@yahoo.com", lat: 47.2456, lng: 23.3486 },
  { country: "Russia", city: "Krasnoiarsk", coordinator: "Larisa Tsurikova", email: "goritsvecha@mail.ru", lat: 56.0153, lng: 92.8932 },
  { country: "Pakistan", city: "Karachi", coordinator: "Sergiu Filat", email: "filatsergiu_me@me.com", lat: 24.8607, lng: 67.0011 },
  { country: "Tajikistan", city: "Dushanbe", coordinator: "Tentiuc Alexei", email: "alexei.tentiuc@gmail.com", lat: 38.5598, lng: 68.787 },
  { country: "Pakistan", city: "Lahore", coordinator: "Sergiu Filat", email: "filatsergiu_me@me.com", lat: 31.5204, lng: 74.3587 },
  { country: "Ukraine", city: "Chernivtsi", coordinator: "Petihacinai Pavel", email: "petih@ukr.net", lat: 48.2915, lng: 25.9403 },
  { country: "Ukraine", city: "Dnipro", coordinator: "Maltev Andrei", email: "a.maltcev68@gmail.com", lat: 48.4647, lng: 35.0462 },
  { country: "Laos", city: "Vientiane", coordinator: "Blendarencu Radu", email: "radu.blendarencu@gmail.com", lat: 17.9757, lng: 102.6331 },
  { country: "Guatemala", city: "Guatemala City", coordinator: "Adan Vasquez", email: "mpicentroamerica@gmail.com", lat: 14.6349, lng: -90.5069 },
  { country: "Moldova", city: "Cărpineni", coordinator: "Rutcovschi Sergiu", email: "sergiu.rutcovschi@gmail.com", lat: 46.7522, lng: 28.3169 },
  { country: "Sri Lanka", city: "Kalkudah", coordinator: "Sergiu Filat", email: "filatsergiu_me@me.com", lat: 7.9236, lng: 81.5389 },
  { country: "Bangladesh", city: "Dhaka", coordinator: "Blendarencu Radu", email: "radu.blendarencu@gmail.com", lat: 23.8103, lng: 90.4125 },
  { country: "Peru", city: "Moyobamba", coordinator: "Blendarencu Radu", email: "radu.blendarencu@gmail.com", lat: -6.0339, lng: -76.9722 },
  { country: "Colombia", city: "Bogota", coordinator: "Luis Pinzon", email: "luisedopinzon@ministeriosprecepto.org", lat: 4.711, lng: -74.0721 },
  { country: "Russia", city: "Krasnodar", coordinator: "Zanin Alexander", email: "zanin.an@gmail.com", lat: 45.0355, lng: 38.9753 },
  { country: "Cambodia", city: "Takéo", coordinator: "Blendarencu Radu", email: "radu.blendarencu@gmail.com", lat: 10.9908, lng: 104.785 },
  { country: "Indonesia", city: "Medan", coordinator: "Samuel pardamean Pakpahan", email: "mrsambc@gmail.com", lat: 3.5952, lng: 98.6722 },
  { country: "Russia", city: "Moscow", coordinator: "Zanin Alexander", email: "zanin.an@gmail.com", lat: 55.7558, lng: 37.6173 },
  { country: "Papua New Guinea", city: "Port Moresby", coordinator: "Blendarencu Radu", email: "radu.blendarencu@gmail.com", lat: -9.4438, lng: 147.1803 },
  { country: "Romania", city: "Tamna", coordinator: "Daba Felicia", email: "feli_marian@yahoo.com", lat: 44.5333, lng: 22.9333 },
  { country: "Myanmar", city: "Yangon", coordinator: "Saw Hudson", email: "u.saw-hudson@total.com", lat: 16.8409, lng: 96.1735 },
  { country: "United States of America", city: "Cleveland", coordinator: "Alena Maslov", email: "alenamaslov1@gmail.com", lat: 41.4993, lng: -81.6944 },
  { country: "Russia", city: "Magnitogorsk", coordinator: "Zakharov Sergey", email: "serezha.zaharov1975@yandex.ru", lat: 53.4186, lng: 59.0472 },
]

export const locationsCountryCount = new Set(locations.map((l) => l.country)).size
